"""GENERATED by scripts/analysis/gen_flow_roles.py. Do not edit by hand.

Per-market cohort roles, keyed by (report, symbol), with a per-report default
for markets the measurement does not cover. Read today for one thing: how retail
(Non-Reportable) behaves on a market, which the /analysis Positioning Index
panel states in its note (via `CotIndexer.get_commercial_flow_data`). The other
roles are the measurement, kept as data; nothing draws them.

Source: docs/analysis/2026-09-26-cot-cohort-roles-propadj.md, measured 2026-09-26 on the propadj price
basis: same-week price correlation of each cohort's weekly net change at a
threshold of 0.15, cohorts under 5% of gross
open interest inert, both fixed before the run. Keys are
`cotmetrics.categories` category keys.
"""

from dataclasses import asdict, dataclass

MEASURED_ON = "2026-09-26"
PX_CORR_THRESHOLD = 0.15
INERT_GROSS_SHARE = 0.05
PRICE_BASIS = "propadj"
SOURCE_DOC = "docs/analysis/2026-09-26-cot-cohort-roles-propadj.md"

SOURCE_MEASURED = "measured"
SOURCE_DEFAULT = "default"


@dataclass(frozen=True)
class FlowRoles:
    """One market's roles. `speculator` empty means no speculator role."""

    report: str
    symbol: object
    speculator: tuple
    counterparty: tuple = ()
    neutral: tuple = ()
    inert: tuple = ()
    retail_behaves: object = None
    source: str = SOURCE_DEFAULT

    def as_dict(self):
        return asdict(self)


DEFAULTS = {
    "disagg": FlowRoles("disagg", None, ('managed_money',)),
    "tff": FlowRoles("tff", None, ('leveraged',)),
}

MEASURED = {
    ("disagg", "CC"): FlowRoles("disagg", "CC", ('managed_money',),
        counterparty=('producer_merchant', 'other_reportable'), neutral=('swap',),
        inert=(), retail_behaves='spec-like',
        source=SOURCE_MEASURED),
    ("disagg", "CL"): FlowRoles("disagg", "CL", ('managed_money',),
        counterparty=('swap', 'other_reportable'), neutral=('producer_merchant',),
        inert=(), retail_behaves='cp-like',
        source=SOURCE_MEASURED),
    ("disagg", "CT"): FlowRoles("disagg", "CT", ('managed_money',),
        counterparty=('producer_merchant',), neutral=('swap', 'other_reportable'),
        inert=(), retail_behaves='spec-like',
        source=SOURCE_MEASURED),
    ("disagg", "GC"): FlowRoles("disagg", "GC", ('managed_money',),
        counterparty=('producer_merchant', 'swap'), neutral=('other_reportable',),
        inert=(), retail_behaves='spec-like',
        source=SOURCE_MEASURED),
    ("disagg", "GF"): FlowRoles("disagg", "GF", ('managed_money',),
        counterparty=('producer_merchant',), neutral=('swap', 'other_reportable'),
        inert=(), retail_behaves='cp-like',
        source=SOURCE_MEASURED),
    ("disagg", "HE"): FlowRoles("disagg", "HE", ('swap', 'managed_money'),
        counterparty=('producer_merchant', 'other_reportable'), neutral=(),
        inert=(), retail_behaves='neutral',
        source=SOURCE_MEASURED),
    ("disagg", "HG"): FlowRoles("disagg", "HG", ('managed_money',),
        counterparty=('producer_merchant', 'swap', 'other_reportable'), neutral=(),
        inert=(), retail_behaves='neutral',
        source=SOURCE_MEASURED),
    ("disagg", "HO"): FlowRoles("disagg", "HO", ('managed_money',),
        counterparty=('producer_merchant', 'swap', 'other_reportable'), neutral=(),
        inert=(), retail_behaves='spec-like',
        source=SOURCE_MEASURED),
    ("disagg", "KC"): FlowRoles("disagg", "KC", ('managed_money',),
        counterparty=('producer_merchant',), neutral=('swap', 'other_reportable'),
        inert=(), retail_behaves='neutral',
        source=SOURCE_MEASURED),
    ("disagg", "LBR"): FlowRoles("disagg", "LBR", ('managed_money', 'other_reportable'),
        counterparty=('producer_merchant',), neutral=('swap',),
        inert=(), retail_behaves='neutral',
        source=SOURCE_MEASURED),
    ("disagg", "LE"): FlowRoles("disagg", "LE", ('managed_money',),
        counterparty=('producer_merchant',), neutral=('swap', 'other_reportable'),
        inert=(), retail_behaves='cp-like',
        source=SOURCE_MEASURED),
    ("disagg", "NG"): FlowRoles("disagg", "NG", ('managed_money',),
        counterparty=('producer_merchant', 'other_reportable'), neutral=('swap',),
        inert=(), retail_behaves='neutral',
        source=SOURCE_MEASURED),
    ("disagg", "OJ"): FlowRoles("disagg", "OJ", ('managed_money',),
        counterparty=('producer_merchant', 'other_reportable'), neutral=(),
        inert=('swap',), retail_behaves='spec-like',
        source=SOURCE_MEASURED),
    ("disagg", "PA"): FlowRoles("disagg", "PA", ('managed_money',),
        counterparty=('producer_merchant', 'swap'), neutral=('other_reportable',),
        inert=(), retail_behaves='spec-like',
        source=SOURCE_MEASURED),
    ("disagg", "PL"): FlowRoles("disagg", "PL", ('managed_money',),
        counterparty=('producer_merchant', 'swap'), neutral=('other_reportable',),
        inert=(), retail_behaves='neutral',
        source=SOURCE_MEASURED),
    ("disagg", "RB"): FlowRoles("disagg", "RB", ('managed_money',),
        counterparty=('producer_merchant', 'other_reportable'), neutral=('swap',),
        inert=(), retail_behaves='spec-like',
        source=SOURCE_MEASURED),
    ("disagg", "SB"): FlowRoles("disagg", "SB", ('managed_money',),
        counterparty=('producer_merchant', 'swap', 'other_reportable'), neutral=(),
        inert=(), retail_behaves='spec-like',
        source=SOURCE_MEASURED),
    ("disagg", "SI"): FlowRoles("disagg", "SI", ('managed_money',),
        counterparty=('producer_merchant', 'swap', 'other_reportable'), neutral=(),
        inert=(), retail_behaves='spec-like',
        source=SOURCE_MEASURED),
    ("disagg", "ZC"): FlowRoles("disagg", "ZC", ('managed_money',),
        counterparty=('producer_merchant',), neutral=('swap', 'other_reportable'),
        inert=(), retail_behaves='neutral',
        source=SOURCE_MEASURED),
    ("disagg", "ZL"): FlowRoles("disagg", "ZL", ('managed_money',),
        counterparty=('producer_merchant',), neutral=('swap', 'other_reportable'),
        inert=(), retail_behaves='spec-like',
        source=SOURCE_MEASURED),
    ("disagg", "ZM"): FlowRoles("disagg", "ZM", ('managed_money',),
        counterparty=('producer_merchant',), neutral=('swap', 'other_reportable'),
        inert=(), retail_behaves='spec-like',
        source=SOURCE_MEASURED),
    ("disagg", "ZS"): FlowRoles("disagg", "ZS", ('managed_money',),
        counterparty=('producer_merchant',), neutral=('swap', 'other_reportable'),
        inert=(), retail_behaves='spec-like',
        source=SOURCE_MEASURED),
    ("disagg", "ZW"): FlowRoles("disagg", "ZW", ('managed_money',),
        counterparty=('producer_merchant', 'other_reportable'), neutral=('swap',),
        inert=(), retail_behaves='neutral',
        source=SOURCE_MEASURED),
    ("tff", "6A"): FlowRoles("tff", "6A", ('asset_manager', 'leveraged'),
        counterparty=('dealer',), neutral=(),
        inert=('other_reportable',), retail_behaves='spec-like',
        source=SOURCE_MEASURED),
    ("tff", "6B"): FlowRoles("tff", "6B", ('asset_manager', 'leveraged'),
        counterparty=('dealer',), neutral=(),
        inert=('other_reportable',), retail_behaves='spec-like',
        source=SOURCE_MEASURED),
    ("tff", "6C"): FlowRoles("tff", "6C", ('asset_manager', 'leveraged'),
        counterparty=('dealer',), neutral=(),
        inert=('other_reportable',), retail_behaves='spec-like',
        source=SOURCE_MEASURED),
    ("tff", "6E"): FlowRoles("tff", "6E", ('asset_manager', 'leveraged'),
        counterparty=('dealer',), neutral=(),
        inert=('other_reportable',), retail_behaves='spec-like',
        source=SOURCE_MEASURED),
    ("tff", "6J"): FlowRoles("tff", "6J", ('asset_manager', 'leveraged'),
        counterparty=('dealer',), neutral=('other_reportable',),
        inert=(), retail_behaves='spec-like',
        source=SOURCE_MEASURED),
    ("tff", "6M"): FlowRoles("tff", "6M", ('leveraged',),
        counterparty=('dealer',), neutral=('asset_manager', 'other_reportable'),
        inert=(), retail_behaves='spec-like',
        source=SOURCE_MEASURED),
    ("tff", "6N"): FlowRoles("tff", "6N", ('asset_manager',),
        counterparty=('dealer',), neutral=('leveraged',),
        inert=('other_reportable',), retail_behaves='spec-like',
        source=SOURCE_MEASURED),
    ("tff", "6S"): FlowRoles("tff", "6S", ('asset_manager', 'leveraged'),
        counterparty=('dealer',), neutral=(),
        inert=('other_reportable',), retail_behaves='spec-like',
        source=SOURCE_MEASURED),
    ("tff", "BTC"): FlowRoles("tff", "BTC", ('asset_manager',),
        counterparty=('leveraged',), neutral=('dealer', 'other_reportable'),
        inert=(), retail_behaves='spec-like',
        source=SOURCE_MEASURED),
    ("tff", "DX"): FlowRoles("tff", "DX", ('asset_manager',),
        counterparty=('dealer',), neutral=('leveraged', 'other_reportable'),
        inert=(), retail_behaves='spec-like',
        source=SOURCE_MEASURED),
    ("tff", "ES"): FlowRoles("tff", "ES", ('asset_manager',),
        counterparty=('leveraged',), neutral=('dealer',),
        inert=('other_reportable',), retail_behaves='neutral',
        source=SOURCE_MEASURED),
    ("tff", "ETH"): FlowRoles("tff", "ETH", ('dealer', 'asset_manager'),
        counterparty=('leveraged',), neutral=(),
        inert=('other_reportable',), retail_behaves='spec-like',
        source=SOURCE_MEASURED),
    ("tff", "NQ"): FlowRoles("tff", "NQ", ('asset_manager',),
        counterparty=('dealer',), neutral=('leveraged',),
        inert=('other_reportable',), retail_behaves='neutral',
        source=SOURCE_MEASURED),
    ("tff", "RTY"): FlowRoles("tff", "RTY", ('asset_manager',),
        counterparty=('dealer',), neutral=('leveraged',),
        inert=('other_reportable',), retail_behaves='neutral',
        source=SOURCE_MEASURED),
    ("tff", "YM"): FlowRoles("tff", "YM", ('asset_manager',),
        counterparty=(), neutral=('dealer', 'leveraged'),
        inert=('other_reportable',), retail_behaves='cp-like',
        source=SOURCE_MEASURED),
    ("tff", "ZB"): FlowRoles("tff", "ZB", ('asset_manager',),
        counterparty=('dealer',), neutral=('leveraged', 'other_reportable'),
        inert=(), retail_behaves='spec-like',
        source=SOURCE_MEASURED),
    ("tff", "ZF"): FlowRoles("tff", "ZF", ('asset_manager',),
        counterparty=('dealer',), neutral=('leveraged',),
        inert=('other_reportable',), retail_behaves='spec-like',
        source=SOURCE_MEASURED),
    ("tff", "ZN"): FlowRoles("tff", "ZN", ('asset_manager',),
        counterparty=('other_reportable',), neutral=('dealer', 'leveraged'),
        inert=(), retail_behaves='spec-like',
        source=SOURCE_MEASURED),
    ("tff", "ZT"): FlowRoles("tff", "ZT", (),
        counterparty=(), neutral=('dealer', 'asset_manager', 'leveraged', 'other_reportable'),
        inert=(), retail_behaves='neutral',
        source=SOURCE_MEASURED),
}


def roles_for(report, symbol=None):
    """The measured entry for (report, symbol), else the report default. Never
    raises for an unknown symbol."""
    entry = MEASURED.get((report, symbol))
    if entry is not None:
        return entry
    default = DEFAULTS[report]
    return FlowRoles(report, symbol, default.speculator)
