"""Regenerate `src/cotmetrics/flow_roles.py` from the propadj cohort-role measurement.

The module it writes is data: for each (report, symbol), which cohorts act as the
speculator, which as the counterparty, which are neutral or inert, and how the retail
(Non-Reportable) cohort behaves. Nothing in it is typed by hand, so a re-measurement is
one command and one diff.

Input, written by `scripts/analysis/cot_cohort_roles_propadj.py`:

    docs/analysis/2026-09-26-cot-cohort-collapse-propadj.csv
        one row per (report, symbol): SPEC_keys, COUNTERPARTY_keys, NEUTRAL_keys,
        inert_keys, retail_behaves

The roles are same-week price correlation of each cohort's weekly net change on the
ratio-adjusted price series, threshold 0.15 and gross-share floor 0.05, both fixed
before the run (docs/analysis/2026-09-26-cot-cohort-roles-propadj.md). The table is
the propadj one, not the cache-close one the "Scope, restated v2" block names: the
cache close is additively back-adjusted, truncated HO, RB and OJ to a fifth to a
third of their history and attenuated every physical's correlation; the user chose
propadj on 2026-09-26. A market the table does not cover gets the per-report default.

Usage (from the cotmetrics checkout):

    python scripts/analysis/gen_flow_roles.py

writes the module in place and prints one line per entry.
"""

import argparse
import os

import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))

COLLAPSE_CSV = os.path.join(ROOT, "docs", "analysis",
                            "2026-09-26-cot-cohort-collapse-propadj.csv")
SOURCE_DOC = "docs/analysis/2026-09-26-cot-cohort-roles-propadj.md"
OUT = os.path.join(ROOT, "src", "cotmetrics", "flow_roles.py")

MEASUREMENT_DATE = "2026-09-26"
PX_CORR_THRESHOLD = 0.15
INERT_GROSS_SHARE = 0.05
PRICE_BASIS = "propadj"

# Per-report default for a market the table does not cover (the held-out markets, or
# a symbol added later): the conventional speculator of each report.
DEFAULTS = {
    "disagg": ("managed_money",),
    "tff": ("leveraged",),
}


def _keys(value):
    if value is None or (isinstance(value, float) and pd.isna(value)):
        return ()
    value = str(value).strip()
    if value in ("", "-"):
        return ()
    return tuple(value.split("+"))


def load(path=COLLAPSE_CSV):
    df = pd.read_csv(path)
    entries = []
    for _, r in df.iterrows():
        behaves = r.get("retail_behaves")
        entries.append(dict(
            report=str(r["report"]), symbol=str(r["sym"]),
            speculator=_keys(r["SPEC_keys"]),
            counterparty=_keys(r["COUNTERPARTY_keys"]),
            neutral=_keys(r["NEUTRAL_keys"]),
            inert=_keys(r["inert_keys"]),
            retail_behaves=None if pd.isna(behaves) else str(behaves),
        ))
    return entries


def render(entries):
    lines = [
        '"""GENERATED by scripts/analysis/gen_flow_roles.py. Do not edit by hand.',
        "",
        "Per-market cohort roles, keyed by (report, symbol), with a per-report default",
        "for markets the measurement does not cover. Read today for one thing: how retail",
        "(Non-Reportable) behaves on a market, which the /analysis Positioning Index",
        "panel states in its note (via `CotIndexer.get_commercial_flow_data`). The other",
        "roles are the measurement, kept as data; nothing draws them.",
        "",
        f"Source: {SOURCE_DOC}, measured {MEASUREMENT_DATE} on the {PRICE_BASIS} price",
        "basis: same-week price correlation of each cohort's weekly net change at a",
        f"threshold of {PX_CORR_THRESHOLD}, cohorts under {INERT_GROSS_SHARE:.0%} of gross",
        "open interest inert, both fixed before the run. Keys are",
        "`cotmetrics.categories` category keys.",
        '"""',
        "",
        "from dataclasses import asdict, dataclass",
        "",
        f'MEASURED_ON = "{MEASUREMENT_DATE}"',
        f"PX_CORR_THRESHOLD = {PX_CORR_THRESHOLD}",
        f"INERT_GROSS_SHARE = {INERT_GROSS_SHARE}",
        f'PRICE_BASIS = "{PRICE_BASIS}"',
        f'SOURCE_DOC = "{SOURCE_DOC}"',
        "",
        'SOURCE_MEASURED = "measured"',
        'SOURCE_DEFAULT = "default"',
        "",
        "",
        "@dataclass(frozen=True)",
        "class FlowRoles:",
        '    """One market\'s roles. `speculator` empty means no speculator role."""',
        "",
        "    report: str",
        "    symbol: object",
        "    speculator: tuple",
        "    counterparty: tuple = ()",
        "    neutral: tuple = ()",
        "    inert: tuple = ()",
        "    retail_behaves: object = None",
        "    source: str = SOURCE_DEFAULT",
        "",
        "    def as_dict(self):",
        "        return asdict(self)",
        "",
        "",
        "DEFAULTS = {",
    ]
    for report, spec in DEFAULTS.items():
        lines.append(f'    "{report}": FlowRoles("{report}", None, {spec!r}),')
    lines += ["}", "", "MEASURED = {"]
    for e in sorted(entries, key=lambda e: (e["report"], e["symbol"])):
        lines.append(
            f'    ("{e["report"]}", "{e["symbol"]}"): FlowRoles('
            f'"{e["report"]}", "{e["symbol"]}", {e["speculator"]!r},')
        lines.append(
            f'        counterparty={e["counterparty"]!r}, neutral={e["neutral"]!r},')
        lines.append(
            f'        inert={e["inert"]!r}, retail_behaves={e["retail_behaves"]!r},')
        lines.append("        source=SOURCE_MEASURED),")
    lines += [
        "}",
        "",
        "",
        "def roles_for(report, symbol=None):",
        '    """The measured entry for (report, symbol), else the report default. Never',
        '    raises for an unknown symbol."""',
        "    entry = MEASURED.get((report, symbol))",
        "    if entry is not None:",
        "        return entry",
        "    default = DEFAULTS[report]",
        "    return FlowRoles(report, symbol, default.speculator)",
        "",
    ]
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the committed module differs from a regeneration")
    args = ap.parse_args()
    entries = load()
    text = render(entries)
    if args.check:
        with open(OUT) as fh:
            same = fh.read() == text
        print("flow_roles.py is current" if same else "flow_roles.py is STALE")
        raise SystemExit(0 if same else 1)
    with open(OUT, "w") as fh:
        fh.write(text)
    for e in entries:
        spec = "+".join(e["speculator"]) or "-"
        print(f'{e["report"]:6s} {e["symbol"]:4s} speculator={spec:30s} '
              f'retail={e["retail_behaves"]}')


if __name__ == "__main__":
    main()
